<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Terra.Engine\Terra.Engine.csproj" />
    <ProjectReference Include="..\Terra.Behaviors.Default\Terra.Behaviors.Default.csproj" />
    <ProjectReference Include="..\Terra.Behaviors.Dsl\Terra.Behaviors.Dsl.csproj" />
    <ProjectReference Include="..\Terra.Presentation.Text\Terra.Presentation.Text.csproj" />
  </ItemGroup>

</Project>
